# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: sshto

before:
  hooks:
    - go mod tidy

builds:
  - id: sshto
    binary: sshto
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: codoworks
    name: sshto
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

homebrew_casks:
  - repository:
      owner: codoworks
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/codoworks/sshto"
    description: "Fast SSH connection manager with interactive TUI"
    license: "MIT"
